-- Fresh target schema for videos with explicit main and subcategories.

create table public.videos (
  id bigint generated by default as identity not null,
  title text not null,
  youtube_url text not null,
  created_at timestamp with time zone not null default now(),
  language_code text null,
  author_name text null,
  start_time integer null,
  end_time integer null,
  constraint videos_pkey primary key (id),
  constraint videos_author_name_fkey foreign key (author_name)
    references public.authors (author_name)
    on update cascade
    on delete restrict,
  constraint videos_language_code_fkey foreign key (language_code)
    references public.languages (language_code)
    on update cascade
    on delete restrict
) tablespace pg_default;

create index if not exists idx_videos_language_code
  on public.videos using btree (language_code) tablespace pg_default
  where language_code is not null;

create index if not exists idx_videos_author_name
  on public.videos using btree (author_name) tablespace pg_default
  where author_name is not null;

create table public.topic_categories (
  id bigint generated by default as identity not null,
  name text not null,
  created_at timestamp with time zone not null default now(),
  constraint topic_categories_pkey primary key (id),
  constraint topic_categories_name_key unique (name)
) tablespace pg_default;

create table public.topic_subcategories (
  id bigint generated by default as identity not null,
  category_id bigint not null,
  name text not null,
  created_at timestamp with time zone not null default now(),
  constraint topic_subcategories_pkey primary key (id),
  constraint topic_subcategories_category_id_name_key unique (category_id, name),
  constraint topic_subcategories_id_category_id_key unique (id, category_id),
  constraint topic_subcategories_category_id_fkey foreign key (category_id)
    references public.topic_categories (id)
    on update cascade
    on delete cascade
) tablespace pg_default;

create index if not exists idx_topic_subcategories_category_id
  on public.topic_subcategories using btree (category_id) tablespace pg_default;

create table public.video_category_assignments (
  id bigint generated by default as identity not null,
  video_id bigint not null,
  category_id bigint not null,
  subcategory_id bigint null,
  created_at timestamp with time zone not null default now(),
  constraint video_category_assignments_pkey primary key (id),
  constraint video_category_assignments_video_id_fkey foreign key (video_id)
    references public.videos (id)
    on update cascade
    on delete cascade,
  constraint video_category_assignments_category_id_fkey foreign key (category_id)
    references public.topic_categories (id)
    on update cascade
    on delete restrict,
  constraint video_category_assignments_subcategory_pair_fkey
    foreign key (subcategory_id, category_id)
    references public.topic_subcategories (id, category_id)
    on update cascade
    on delete restrict
) tablespace pg_default;

create index if not exists idx_video_category_assignments_video_id
  on public.video_category_assignments using btree (video_id) tablespace pg_default;

create index if not exists idx_video_category_assignments_category_id
  on public.video_category_assignments using btree (category_id) tablespace pg_default;

create index if not exists idx_video_category_assignments_subcategory_id
  on public.video_category_assignments using btree (subcategory_id) tablespace pg_default
  where subcategory_id is not null;

create unique index if not exists video_category_assignments_video_category_root_key
  on public.video_category_assignments using btree (video_id, category_id)
  where subcategory_id is null;

create unique index if not exists video_category_assignments_video_category_subcategory_key
  on public.video_category_assignments using btree (video_id, category_id, subcategory_id)
  where subcategory_id is not null;

create or replace view public.video_category_tree as
select
  videos.id as video_id,
  videos.title as video_title,
  topic_categories.id as category_id,
  topic_categories.name as category_name,
  topic_subcategories.id as subcategory_id,
  topic_subcategories.name as subcategory_name,
  case
    when topic_subcategories.id is null then topic_categories.name
    else topic_categories.name || ' > ' || topic_subcategories.name
  end as topic_label
from public.videos
join public.video_category_assignments
  on video_category_assignments.video_id = videos.id
join public.topic_categories
  on topic_categories.id = video_category_assignments.category_id
left join public.topic_subcategories
  on topic_subcategories.id = video_category_assignments.subcategory_id;
