-- Fresh target schema for normalized video topics.
-- Use this only when creating the tables from scratch.

create table public.videos (
  id bigint generated by default as identity not null,
  title text not null,
  youtube_url text not null,
  created_at timestamp with time zone not null default now(),
  language_code text null,
  author_name text null,
  start_time integer null,
  end_time integer null,
  constraint videos_pkey primary key (id),
  constraint videos_author_name_fkey foreign key (author_name)
    references public.authors (author_name)
    on update cascade
    on delete restrict,
  constraint videos_language_code_fkey foreign key (language_code)
    references public.languages (language_code)
    on update cascade
    on delete restrict
) tablespace pg_default;

create index if not exists idx_videos_language_code
  on public.videos using btree (language_code) tablespace pg_default
  where language_code is not null;

create index if not exists idx_videos_author_name
  on public.videos using btree (author_name) tablespace pg_default
  where author_name is not null;

create table public.topics (
  id bigint generated by default as identity not null,
  name text not null,
  parent_topic_id bigint null,
  created_at timestamp with time zone not null default now(),
  constraint topics_pkey primary key (id),
  constraint topics_name_key unique (name),
  constraint topics_parent_topic_fkey foreign key (parent_topic_id)
    references public.topics (id)
    on update cascade
    on delete restrict,
  constraint topics_no_self_parent check (
    parent_topic_id is null
    or parent_topic_id <> id
  )
) tablespace pg_default;

create index if not exists idx_topics_parent_topic_id
  on public.topics using btree (parent_topic_id) tablespace pg_default
  where parent_topic_id is not null;

create table public.video_topics (
  video_id bigint not null,
  topic_id bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint video_topics_pkey primary key (video_id, topic_id),
  constraint video_topics_video_id_fkey foreign key (video_id)
    references public.videos (id)
    on update cascade
    on delete cascade,
  constraint video_topics_topic_id_fkey foreign key (topic_id)
    references public.topics (id)
    on update cascade
    on delete restrict
) tablespace pg_default;

create index if not exists idx_video_topics_topic_id
  on public.video_topics using btree (topic_id) tablespace pg_default;

create or replace view public.video_topic_tree as
select
  videos.id as video_id,
  videos.title as video_title,
  child.id as topic_id,
  child.name as topic_name,
  parent.id as parent_topic_id,
  parent.name as parent_topic_name
from public.videos
join public.video_topics on video_topics.video_id = videos.id
join public.topics child on child.id = video_topics.topic_id
left join public.topics parent on parent.id = child.parent_topic_id;

create or replace function public.video_distinct_topics(p_lang text default null)
returns table(topic text)
language sql
stable
security invoker
as $$
  select distinct topics.name as topic
  from public.videos
  join public.video_topics on video_topics.video_id = videos.id
  join public.topics on topics.id = video_topics.topic_id
  where (p_lang is null or videos.language_code = p_lang)
  order by 1;
$$;
