-- Normalize video topics into hierarchical topics plus a many-to-many join table.
-- Safe migration path for the current videos.video_topic text column.

begin;

create table if not exists public.topics (
  id bigint generated by default as identity not null,
  name text not null,
  parent_topic_id bigint null,
  created_at timestamp with time zone not null default now(),
  constraint topics_pkey primary key (id),
  constraint topics_name_key unique (name),
  constraint topics_parent_topic_fkey foreign key (parent_topic_id)
    references public.topics (id)
    on update cascade
    on delete restrict,
  constraint topics_no_self_parent check (
    parent_topic_id is null
    or parent_topic_id <> id
  )
) tablespace pg_default;

create index if not exists idx_topics_parent_topic_id
  on public.topics using btree (parent_topic_id) tablespace pg_default
  where parent_topic_id is not null;

create unique index if not exists topics_name_key
  on public.topics using btree (name) tablespace pg_default;

create table if not exists public.video_topics (
  video_id bigint not null,
  topic_id bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint video_topics_pkey primary key (video_id, topic_id),
  constraint video_topics_video_id_fkey foreign key (video_id)
    references public.videos (id)
    on update cascade
    on delete cascade,
  constraint video_topics_topic_id_fkey foreign key (topic_id)
    references public.topics (id)
    on update cascade
    on delete restrict
) tablespace pg_default;

create index if not exists idx_video_topics_topic_id
  on public.video_topics using btree (topic_id) tablespace pg_default;

with split_topics as (
  select distinct
    btrim(split_topic.topic) as topic_name
  from public.videos v
  cross join lateral regexp_split_to_table(
    coalesce(v.video_topic, ''),
    ','
  ) as split_topic(topic)
  where nullif(btrim(split_topic.topic), '') is not null
)
insert into public.topics (name)
select topic_name
from split_topics
on conflict (name) do nothing;

with split_topics as (
  select distinct
    v.id as video_id,
    btrim(split_topic.topic) as topic_name
  from public.videos v
  cross join lateral regexp_split_to_table(
    coalesce(v.video_topic, ''),
    ','
  ) as split_topic(topic)
  where nullif(btrim(split_topic.topic), '') is not null
)
insert into public.video_topics (video_id, topic_id)
select
  split_topics.video_id,
  topics.id as topic_id
from split_topics
join public.topics on topics.name = split_topics.topic_name
on conflict (video_id, topic_id) do nothing;

create or replace function public.sync_video_topics_from_video_topic()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  topic_names text[];
begin
  delete from public.video_topics
  where video_id = new.id;

  select coalesce(array_agg(distinct topic_name), '{}')
  into topic_names
  from (
    select nullif(btrim(split_topic.topic), '') as topic_name
    from regexp_split_to_table(
      coalesce(new.video_topic, ''),
      ','
    ) as split_topic(topic)
  ) parsed_topics
  where topic_name is not null;

  insert into public.topics (name)
  select topic_name.name
  from unnest(topic_names) as topic_name(name)
  on conflict (name) do nothing;

  insert into public.video_topics (video_id, topic_id)
  select
    new.id,
    topics.id
  from public.topics
  join unnest(topic_names) as topic_name(name)
    on topic_name.name = topics.name
  on conflict (video_id, topic_id) do nothing;

  return new;
end;
$$;

drop trigger if exists videos_sync_video_topics on public.videos;

create trigger videos_sync_video_topics
after insert or update of video_topic on public.videos
for each row
execute function public.sync_video_topics_from_video_topic();

create or replace function public.video_distinct_topics(p_lang text default null)
returns table(topic text)
language sql
stable
security invoker
as $$
  select distinct topics.name as topic
  from public.videos
  join public.video_topics on video_topics.video_id = videos.id
  join public.topics on topics.id = video_topics.topic_id
  where (p_lang is null or videos.language_code = p_lang)
  order by 1;
$$;

create or replace view public.video_topic_tree as
select
  videos.id as video_id,
  videos.title as video_title,
  child.id as topic_id,
  child.name as topic_name,
  parent.id as parent_topic_id,
  parent.name as parent_topic_name
from public.videos
join public.video_topics on video_topics.video_id = videos.id
join public.topics child on child.id = video_topics.topic_id
left join public.topics parent on parent.id = child.parent_topic_id;

select setval(
  pg_get_serial_sequence('public.topics', 'id'),
  coalesce((select max(id) from public.topics), 1),
  exists(select 1 from public.topics)
);

commit;

-- After the app has been changed to read/write public.video_topics directly,
-- you can remove the legacy text column with:
--
-- drop trigger if exists videos_sync_video_topics on public.videos;
-- drop function if exists public.sync_video_topics_from_video_topic();
-- drop index if exists public.idx_videos_video_topic;
-- alter table public.videos drop column if exists video_topic;
