-- Replace the self-referencing topics table with explicit category tables.
-- Final model:
--   videos
--   topic_categories
--   topic_subcategories
--   video_category_assignments

begin;

create table if not exists public.topic_categories (
  id bigint generated by default as identity not null,
  name text not null,
  created_at timestamp with time zone not null default now(),
  constraint topic_categories_pkey primary key (id),
  constraint topic_categories_name_key unique (name)
) tablespace pg_default;

create table if not exists public.topic_subcategories (
  id bigint generated by default as identity not null,
  category_id bigint not null,
  name text not null,
  created_at timestamp with time zone not null default now(),
  constraint topic_subcategories_pkey primary key (id),
  constraint topic_subcategories_category_id_name_key unique (category_id, name),
  constraint topic_subcategories_id_category_id_key unique (id, category_id),
  constraint topic_subcategories_category_id_fkey foreign key (category_id)
    references public.topic_categories (id)
    on update cascade
    on delete cascade
) tablespace pg_default;

create table if not exists public.video_category_assignments (
  id bigint generated by default as identity not null,
  video_id bigint not null,
  category_id bigint not null,
  subcategory_id bigint null,
  created_at timestamp with time zone not null default now(),
  constraint video_category_assignments_pkey primary key (id),
  constraint video_category_assignments_video_id_fkey foreign key (video_id)
    references public.videos (id)
    on update cascade
    on delete cascade,
  constraint video_category_assignments_category_id_fkey foreign key (category_id)
    references public.topic_categories (id)
    on update cascade
    on delete restrict,
  constraint video_category_assignments_subcategory_pair_fkey
    foreign key (subcategory_id, category_id)
    references public.topic_subcategories (id, category_id)
    on update cascade
    on delete restrict
) tablespace pg_default;

create index if not exists idx_topic_subcategories_category_id
  on public.topic_subcategories using btree (category_id) tablespace pg_default;

create index if not exists idx_video_category_assignments_video_id
  on public.video_category_assignments using btree (video_id) tablespace pg_default;

create index if not exists idx_video_category_assignments_category_id
  on public.video_category_assignments using btree (category_id) tablespace pg_default;

create index if not exists idx_video_category_assignments_subcategory_id
  on public.video_category_assignments using btree (subcategory_id) tablespace pg_default
  where subcategory_id is not null;

create unique index if not exists video_category_assignments_video_category_root_key
  on public.video_category_assignments using btree (video_id, category_id)
  where subcategory_id is null;

create unique index if not exists video_category_assignments_video_category_subcategory_key
  on public.video_category_assignments using btree (video_id, category_id, subcategory_id)
  where subcategory_id is not null;

insert into public.topics (name)
values
  ('Gottesdienst'),
  ('Islamische Monate'),
  ('Worship')
on conflict (name) do nothing;

with topic_mapping(child_name, parent_name) as (
  values
    ('Seelische Krankheiten', 'Selbstverbesserung'),
    ('Dunya-Schmerz', 'Selbstverbesserung'),
    ('Tod', 'Selbstverbesserung'),
    ('Ehe', 'Alltag'),
    ('Gesellschaft', 'Alltag'),
    ('Schwestern', 'Alltag'),
    ('Brüder', 'Alltag'),
    ('Kindererziehung', 'Alltag'),
    ('Gebet', 'Gottesdienst'),
    ('Mustahabat', 'Gottesdienst'),
    ('Pflichten', 'Gottesdienst'),
    ('Bittgebete', 'Gottesdienst'),
    ('Monat Ramadan', 'Islamische Monate'),
    ('Monat Schaʿbān', 'Islamische Monate'),
    ('Monat Rajab', 'Islamische Monate'),
    ('Ashura-Muharram: Ganzer Majlis', 'Muharram'),
    ('Ashura-Muharram: whole Majlis', 'Muharram'),
    ('Wichtige Persönlichkeiten', 'Muharram'),
    ('History', 'Muharram'),
    ('Patience', 'Self improvement'),
    ('Success', 'Self improvement'),
    ('Paradise', 'Self improvement'),
    ('Hereafter', 'Islamic Worldview Lecture Series'),
    ('Shaytan', 'Islamic Worldview Lecture Series'),
    ('Prayer', 'Worship'),
    ('Day of Ghadeer', 'Ahlulbayt (as)'),
    ('النجاح', 'تطوير الذات'),
    ('الجنة', 'تطوير الذات'),
    ('الروحانية', 'تطوير الذات')
)
update public.topics child
set parent_topic_id = parent.id
from topic_mapping
join public.topics parent on parent.name = topic_mapping.parent_name
where child.name = topic_mapping.child_name
  and child.parent_topic_id is distinct from parent.id;

with category_source as (
  select distinct topics.name
  from public.topics
  where topics.parent_topic_id is null

  union

  select distinct parent.name
  from public.topics child
  join public.topics parent on parent.id = child.parent_topic_id
)
insert into public.topic_categories (name)
select category_source.name
from category_source
where nullif(btrim(category_source.name), '') is not null
on conflict (name) do nothing;

insert into public.topic_subcategories (category_id, name)
select distinct
  topic_categories.id as category_id,
  child.name
from public.topics child
join public.topics parent on parent.id = child.parent_topic_id
join public.topic_categories on topic_categories.name = parent.name
where nullif(btrim(child.name), '') is not null
on conflict (category_id, name) do nothing;

insert into public.video_category_assignments (
  video_id,
  category_id,
  subcategory_id
)
select distinct
  video_topics.video_id,
  topic_categories.id as category_id,
  null::bigint as subcategory_id
from public.video_topics
join public.topics root_topic on root_topic.id = video_topics.topic_id
join public.topic_categories on topic_categories.name = root_topic.name
where root_topic.parent_topic_id is null
  and not exists (
    select 1
    from public.video_topics child_assignment
    join public.topics child_topic
      on child_topic.id = child_assignment.topic_id
    where child_assignment.video_id = video_topics.video_id
      and child_topic.parent_topic_id = root_topic.id
  )
on conflict do nothing;

insert into public.video_category_assignments (
  video_id,
  category_id,
  subcategory_id
)
select distinct
  video_topics.video_id,
  topic_categories.id as category_id,
  topic_subcategories.id as subcategory_id
from public.video_topics
join public.topics child_topic on child_topic.id = video_topics.topic_id
join public.topics parent_topic on parent_topic.id = child_topic.parent_topic_id
join public.topic_categories on topic_categories.name = parent_topic.name
join public.topic_subcategories
  on topic_subcategories.category_id = topic_categories.id
  and topic_subcategories.name = child_topic.name
on conflict do nothing;

drop function if exists public.video_distinct_topics(text);

drop view if exists public.video_topic_tree;

create or replace view public.video_category_tree as
select
  videos.id as video_id,
  videos.title as video_title,
  topic_categories.id as category_id,
  topic_categories.name as category_name,
  topic_subcategories.id as subcategory_id,
  topic_subcategories.name as subcategory_name,
  case
    when topic_subcategories.id is null then topic_categories.name
    else topic_categories.name || ' > ' || topic_subcategories.name
  end as topic_label
from public.videos
join public.video_category_assignments
  on video_category_assignments.video_id = videos.id
join public.topic_categories
  on topic_categories.id = video_category_assignments.category_id
left join public.topic_subcategories
  on topic_subcategories.id = video_category_assignments.subcategory_id;

select setval(
  pg_get_serial_sequence('public.topic_categories', 'id'),
  coalesce((select max(id) from public.topic_categories), 1),
  exists(select 1 from public.topic_categories)
);

select setval(
  pg_get_serial_sequence('public.topic_subcategories', 'id'),
  coalesce((select max(id) from public.topic_subcategories), 1),
  exists(select 1 from public.topic_subcategories)
);

select setval(
  pg_get_serial_sequence('public.video_category_assignments', 'id'),
  coalesce((select max(id) from public.video_category_assignments), 1),
  exists(select 1 from public.video_category_assignments)
);

drop table if exists public.video_topics;
drop table if exists public.topics;

alter table public.videos
  drop column if exists video_topic;

commit;
